### PR TITLE
Prepare for `polars` 0.19.0

### PR DESCRIPTION
**Pull request by etiennebacher**

### CODE REVIEW

**Review by eitsupi — COMMENTED** [review]
This is obviously failing because you are trying to install binaries built with Ubuntu 24.04 on Ubuntu 22.04?

**Comment by etiennebacher** [comment]
But that wasn't failing before?

**Comment by eitsupi** [comment]
I don't know if it had failed before, but after R-universe switched to Ubuntu 24.04, I believe the binaries built using glibc were not compatible with Ubuntu 22.04. That is not specific to this package.

**Comment by etiennebacher** [comment]
I will probably need to update the workflow to be on 24.04, but we should also make it clearer in polars docs which platform and version can install binaries from R-universe. Currently, the Ubuntu versions aren't mentioned anywhere, which is why I thought if the install works then my setup (in CI) must be fine

**Comment by etiennebacher** [comment]
> I don't know if it had failed before, but after R-universe switched to Ubuntu 24.04, I believe the binaries built using glibc were not compatible with Ubuntu 22.04. That is not specific to this package.

Ah I missed this upgrade

**Comment by eitsupi** [comment]
> I will probably need to update the workflow to be on 24.04, but we should also make it clearer in polars docs which platform and version can install binaries from R-universe. Currently, the Ubuntu versions aren't mentioned anywhere, which is why I thought if the install works then my setup (in CI) must be fine

The polars documentation does not recommend specifying URLs for Ubuntu binaries. This is because it is only available under very limited conditions, and we have no control over it.

https://github.com/pola-rs/r-polars/blob/9c5ddfafaffbb15b2c74e2c5c7a68f0ef1affe01/vignettes/install.Rmd#L28-L39

**Comment by etiennebacher** [comment]
I had tried without the URL in 9af957be045627bd812738a7efe9648e3b96eb12, but forgot to add the `NOT_CRAN` line, which is why it was looking for the Rust installation (and didn't find it)

**Comment by eitsupi** [comment]
Unless you are fully familiar with R-universe's CI, it is not recommended to install packages from that URL. Same as my previous comment.
https://github.com/etiennebacher/tidypolars/pull/115#issuecomment-2104595471

**Comment by etiennebacher** [comment]
Alright, everything's good now and I updated the installation instructions in the README too, thanks again for your help on this @eitsupi !

**Pull request merged**
