### PR TITLE
funs: add support for `stringr::str_trunc()`

### PR DESCRIPTION
**Pull request by etiennebacher**

### CODE REVIEW

**Comment by eitsupi** [comment]
Note that polars > 0.16.1 isn't available for arm64 macOS via R-universe.
See r-universe-org/help#398

**Comment by eitsupi** [comment]
A simple workaround is to change the runner to macos-12; polars must be installed from source to continue using macos-latest.

**Comment by etiennebacher** [comment]
Thanks for the info and the workaround, that should do the trick for R CMD check but the covr workflow runs on Ubuntu. Do you know why it fails in this case?

**Comment by eitsupi** [comment]
Quick glance, perhaps you are using Ubuntu 22.04 with r2u?
R-universe has switched to Ubuntu 24.04, and I think this is due to a change in compatibility (or assumed URL) of Ubuntu binaries.

In fact, I think it is far less likely to cause problems to source install polars with `NOT_CRAN=ture`.

Like this.
https://github.com/rpolars/r-polarssql/blob/76750e97ea43330686089eb273887eea42b2bfbc/.github/workflows/pkgdown.yml#L42-L51

**Comment by eitsupi** [comment]
That's why:

image

So for Ubuntu, 0.16.4 is not found at the traditional URL (for jammy), and for macos-latest, only 0.16.1 is found.

**Comment by eitsupi** [comment]
As far as I have tried polars I have no problem installing the 24.04 binary on R-universe on Ubuntu 22.04. In other words, I think it works just by modifying the URL.

By the way, two years ago when they changed from 20.04 to 22.04, the binaries were no longer compatible.
So I always recommend to do a source install.

**Comment by etiennebacher** [comment]
I can't figure out how to fix this covr workflow. The session info tab shows that it's R 4.4, and your screenshot shows that for R 4.4 polars 0.16.4 is available. So then why do I have a message "Warning message: package ‘polars’ is not available for this version of R" (https://github.com/etiennebacher/tidypolars/actions/runs/9032638186/job/24821212140?pr=115#step:5:677)?

Also I opened this PR not even 20 min after merging #114 where everything worked fine so I don't understand why this fails now

**Comment by eitsupi** [comment]
@etiennebacher Please check carefully the image I have uploaded.
There is no binary URL for R `4.4` for `jammy` on R-universe, and R `4.3` for `jammy` doesn't have polars `0.16.4`.

**Comment by eitsupi** [comment]
Again, I recommend source installation from a non-binary URL along with the r-lib action.
There is little advantage to a binary install since the installation is quick since the binary library is obtained from the GitHub release.

**Pull request merged**
